import { BarCompare } from './BarCompare'
import { CompareSplit } from './CompareSplit'
import { MetricFocus } from './MetricFocus'
import { ProfileReveal } from './ProfileReveal'
import { ShareRing } from './ShareRing'
import { StepFlow } from './StepFlow'
import type {
  BarCompareParams,
  CompareSplitParams,
  MetricFocusParams,
  MotionDefinition,
  MotionId,
  ProfileRevealParams,
  ShareRingParams,
  StepFlowParams,
} from './types'

type RegisteredMotion =
  | MotionDefinition<MetricFocusParams>
  | MotionDefinition<CompareSplitParams>
  | MotionDefinition<ProfileRevealParams>
  | MotionDefinition<BarCompareParams>
  | MotionDefinition<ShareRingParams>
  | MotionDefinition<StepFlowParams>

export const motionRegistry: RegisteredMotion[] = [
  {
    id: 'metric-focus',
    index: '01',
    name: '核心指标',
    category: '数据 / 指标',
    description: '核心数字动效',
    component: MetricFocus,
    defaults: {
      eyebrow: '季度增长',
      value: 248,
      prefix: '+',
      suffix: '%',
      description: '同比增长',
      trend: '上升 32.4 个百分点',
      decimals: 0,
      duration: 1.4,
    },
    controls: [
      { type: 'text', key: 'eyebrow', label: '指标名称', maxLength: 24 },
      { type: 'number', key: 'value', label: '核心数值', min: 0, max: 999, step: 1 },
      { type: 'text', key: 'prefix', label: '前缀', maxLength: 2 },
      { type: 'text', key: 'suffix', label: '后缀', maxLength: 4 },
      { type: 'text', key: 'description', label: '说明文字', maxLength: 16 },
      { type: 'text', key: 'trend', label: '趋势文字', maxLength: 16 },
      { type: 'number', key: 'decimals', label: '小数位数', min: 0, max: 2, step: 1 },
      { type: 'number', key: 'duration', label: '动画时长', min: 0.6, max: 3, step: 0.1, suffix: '秒' },
    ],
  },
  {
    id: 'compare-split',
    index: '02',
    name: '对比卡片',
    category: '双项 / 对比',
    description: '左右对比卡',
    component: CompareSplit,
    defaults: {
      title: '转化率',
      leftLabel: '优化前',
      leftValue: 42,
      rightLabel: '优化后',
      rightValue: 86,
      suffix: '%',
      conclusion: '提升 2.05 倍',
      emphasis: 'right',
      split: 50,
      duration: 1.5,
    },
    controls: [
      { type: 'text', key: 'title', label: '对比标题', maxLength: 24 },
      { type: 'text', key: 'leftLabel', label: '左侧标签', maxLength: 14 },
      { type: 'number', key: 'leftValue', label: '左侧数值', min: 0, max: 100, step: 1 },
      { type: 'text', key: 'rightLabel', label: '右侧标签', maxLength: 14 },
      { type: 'number', key: 'rightValue', label: '右侧数值', min: 0, max: 100, step: 1 },
      { type: 'text', key: 'suffix', label: '数值后缀', maxLength: 4 },
      { type: 'text', key: 'conclusion', label: '结论文字', maxLength: 24 },
      {
        type: 'select',
        key: 'emphasis',
        label: '强调区域',
        options: [
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
        ],
      },
      { type: 'number', key: 'split', label: '分割位置', min: 32, max: 68, step: 1, suffix: '%' },
      { type: 'number', key: 'duration', label: '动画时长', min: 0.6, max: 3, step: 0.1, suffix: '秒' },
    ],
  },
  {
    id: 'profile-reveal',
    index: '03',
    name: '人物信息',
    category: '叙事 / 人物',
    description: '逐句动态信息卡',
    component: ProfileReveal,
    defaults: {
      category: '创作者 / 人物档案',
      descriptor: '独立开发者 · 产品构建者',
      overline: '公开构建',
      title: '公开构建者',
      fact1: '没有庞大团队',
      fact1Note: '小型团队',
      fact2: '没有巨额预算',
      fact2Note: '轻量预算',
      fact3: '只靠持续交付',
      fact3Note: '每周交付',
      status: '档案 / 已确认',
      duration: 6.4,
    },
    controls: [
      { type: 'text', key: 'category', label: '身份眉题', maxLength: 24 },
      { type: 'text', key: 'descriptor', label: '身份说明', maxLength: 24 },
      { type: 'text', key: 'overline', label: '标题引导', maxLength: 24 },
      { type: 'text', key: 'title', label: '核心标题', maxLength: 12 },
      { type: 'text', key: 'fact1', label: '信息一', maxLength: 16 },
      { type: 'text', key: 'fact1Note', label: '信息一注释', maxLength: 20 },
      { type: 'text', key: 'fact2', label: '信息二', maxLength: 16 },
      { type: 'text', key: 'fact2Note', label: '信息二注释', maxLength: 20 },
      { type: 'text', key: 'fact3', label: '信息三', maxLength: 16 },
      { type: 'text', key: 'fact3Note', label: '信息三注释', maxLength: 20 },
      { type: 'text', key: 'status', label: '状态文字', maxLength: 24 },
      { type: 'number', key: 'duration', label: '循环时长', min: 5.2, max: 10, step: 0.2, suffix: '秒' },
    ],
  },
  {
    id: 'bar-compare',
    index: '04',
    name: '柱状对比',
    category: '数据 / 柱状',
    description: '柱状数据对比',
    component: BarCompare,
    defaults: {
      eyebrow: '04 / 数据对比',
      title: '季度增长',
      item1Label: '第一季',
      item1Value: 32,
      item2Label: '第二季',
      item2Value: 48,
      item3Label: '第三季',
      item3Value: 67,
      item4Label: '第四季',
      item4Value: 86,
      suffix: '%',
      focusIndex: '4',
      resultLabel: '最高值',
      resultNote: '第四季 / 上升18点',
      duration: 5.8,
    },
    controls: [
      { type: 'text', key: 'eyebrow', label: '分类眉题', maxLength: 24 },
      { type: 'text', key: 'title', label: '对比标题', maxLength: 16 },
      { type: 'text', key: 'item1Label', label: '数据一名称', maxLength: 8 },
      { type: 'number', key: 'item1Value', label: '数据一数值', min: 0, max: 9999, step: 1 },
      { type: 'text', key: 'item2Label', label: '数据二名称', maxLength: 8 },
      { type: 'number', key: 'item2Value', label: '数据二数值', min: 0, max: 9999, step: 1 },
      { type: 'text', key: 'item3Label', label: '数据三名称', maxLength: 8 },
      { type: 'number', key: 'item3Value', label: '数据三数值', min: 0, max: 9999, step: 1 },
      { type: 'text', key: 'item4Label', label: '数据四名称', maxLength: 8 },
      { type: 'number', key: 'item4Value', label: '数据四数值', min: 0, max: 9999, step: 1 },
      { type: 'text', key: 'suffix', label: '数值后缀', maxLength: 4 },
      {
        type: 'select',
        key: 'focusIndex',
        label: '重点数据',
        options: [
          { label: '数据一', value: '1' },
          { label: '数据二', value: '2' },
          { label: '数据三', value: '3' },
          { label: '数据四', value: '4' },
        ],
      },
      { type: 'text', key: 'resultLabel', label: '结论标签', maxLength: 12 },
      { type: 'text', key: 'resultNote', label: '结论说明', maxLength: 18 },
      { type: 'number', key: 'duration', label: '循环时长', min: 4.8, max: 10, step: 0.2, suffix: '秒' },
    ],
  },
  {
    id: 'share-ring',
    index: '05',
    name: '环形占比',
    category: '数据 / 占比',
    description: '环形占比分析',
    component: ShareRing,
    defaults: {
      eyebrow: '05 / 占比分析',
      title: '用户构成',
      item1Label: '核心用户',
      item1Value: 62,
      item2Label: '成长用户',
      item2Value: 20,
      item3Label: '观察用户',
      item3Value: 12,
      item4Label: '其他',
      item4Value: 6,
      focusIndex: '1',
      centerLabel: '核心人群',
      resultLabel: '主要占比',
      resultNote: '排名 / 第一',
      duration: 6,
    },
    controls: [
      { type: 'text', key: 'eyebrow', label: '分类眉题', maxLength: 24 },
      { type: 'text', key: 'title', label: '占比标题', maxLength: 16 },
      { type: 'text', key: 'item1Label', label: '占比一名称', maxLength: 8 },
      { type: 'number', key: 'item1Value', label: '占比一数值', min: 0, max: 10000, step: 1 },
      { type: 'text', key: 'item2Label', label: '占比二名称', maxLength: 8 },
      { type: 'number', key: 'item2Value', label: '占比二数值', min: 0, max: 10000, step: 1 },
      { type: 'text', key: 'item3Label', label: '占比三名称', maxLength: 8 },
      { type: 'number', key: 'item3Value', label: '占比三数值', min: 0, max: 10000, step: 1 },
      { type: 'text', key: 'item4Label', label: '占比四名称', maxLength: 8 },
      { type: 'number', key: 'item4Value', label: '占比四数值', min: 0, max: 10000, step: 1 },
      {
        type: 'select',
        key: 'focusIndex',
        label: '主要占比',
        options: [
          { label: '占比一', value: '1' },
          { label: '占比二', value: '2' },
          { label: '占比三', value: '3' },
          { label: '占比四', value: '4' },
        ],
      },
      { type: 'text', key: 'centerLabel', label: '中心标签', maxLength: 12 },
      { type: 'text', key: 'resultLabel', label: '结论标签', maxLength: 12 },
      { type: 'text', key: 'resultNote', label: '结论说明', maxLength: 18 },
      { type: 'number', key: 'duration', label: '循环时长', min: 5, max: 10, step: 0.2, suffix: '秒' },
    ],
  },
  {
    id: 'step-flow',
    index: '06',
    name: '步骤流程',
    category: '流程 / 步骤',
    description: '步骤流程讲解',
    component: StepFlow,
    defaults: {
      eyebrow: '06 / 流程图',
      title: '发布流程',
      step1: '明确目标',
      step2: '准备内容',
      step3: '构建版本',
      step4: '验证结果',
      step5: '正式发布',
      focusStep: '3',
      statusLabel: '当前步骤',
      statusNote: '构建 / 进行中',
      stepDuration: 1.1,
    },
    controls: [
      { type: 'text', key: 'eyebrow', label: '分类眉题', maxLength: 24 },
      { type: 'text', key: 'title', label: '流程标题', maxLength: 16 },
      { type: 'text', key: 'step1', label: '步骤一', maxLength: 12 },
      { type: 'text', key: 'step2', label: '步骤二', maxLength: 12 },
      { type: 'text', key: 'step3', label: '步骤三', maxLength: 12 },
      { type: 'text', key: 'step4', label: '步骤四', maxLength: 12 },
      { type: 'text', key: 'step5', label: '步骤五', maxLength: 12 },
      {
        type: 'select',
        key: 'focusStep',
        label: '初始焦点',
        options: [
          { label: '步骤一', value: '1' },
          { label: '步骤二', value: '2' },
          { label: '步骤三', value: '3' },
          { label: '步骤四', value: '4' },
          { label: '步骤五', value: '5' },
        ],
      },
      { type: 'text', key: 'statusLabel', label: '状态标签', maxLength: 12 },
      { type: 'text', key: 'statusNote', label: '状态说明', maxLength: 18 },
      { type: 'number', key: 'stepDuration', label: '单步停留', min: 0.7, max: 2.4, step: 0.1, suffix: '秒' },
    ],
  },
]

export function getMotionDefinition(id: MotionId) {
  return motionRegistry.find((motion) => motion.id === id) ?? motionRegistry[0]
}
